/**
 * Données de démonstration utilisées quand l'API WordPress n'est pas disponible.
 * En production, toutes les données viennent de WordPress.
 */
import type { Project, Fragment, ResearchQuestion, Text } from "./api";

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "trois-doigts", wp_id: 0, title: "À trois doigts", category: "anim.", status: "expérimentation",
    year: "2024", question: "Comment représenter un corps sans le réduire à son anatomie ?",
    manifeste: "Un corps incomplet qui découvre que le manque peut devenir un mouvement.",
    description: "Un court métrage d'animation sur ce que l'absence configure.",
    lastUpdated: "12 jan. 2025", themes: ["corps","handicap","transformation","perception"],
    tags: ["Animation","Corps","Narration"],
    image: "https://images.unsplash.com/photo-1585571290034-3f59a2568563?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 14,
    journal: [
      { date: "10 jan. 2025", title: "Premier test de rig", content: "Le rig à trois doigts génère des mouvements inattendus.", type: "découverte" },
      { date: "5 jan. 2025", title: "Blocage sur la prise d'objet", content: "Comment la main attrape un verre sans le quatrième doigt ?", type: "difficulté" },
    ],
    maintenant: { cherche: "Une gestuelle propre au corps incomplet.", avancee: "Le rig de la main fonctionne.", bloque: "La séquence de la tasse.", prochaine: "Animer la séquence d'ouverture.", question: "Le manque peut-il être filmé sans qu'on le remarque immédiatement ?" },
    references: [{ title: "Corps et âme", author: "Didier Fassin", year: "2015" }],
  },
  {
    id: "oeil-matiere", wp_id: 0, title: "L'Œil de la matière", category: "install.", status: "production",
    year: "2023", question: "Une matière peut-elle nous regarder ?",
    manifeste: "Quand la caméra devient peau, et la lumière, organe.",
    description: "Une installation interrogeant les rapports entre corps, lumière, matière et dispositif optique.",
    lastUpdated: "8 jan. 2025", themes: ["matière","perception","lumière","corps"],
    tags: ["Installation","Vidéo","Corps"],
    image: "https://images.unsplash.com/photo-1588203379102-1a06c7d2ba1f?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 21,
    journal: [{ date: "8 jan. 2025", title: "Test résine + fibre optique", content: "La résine translucide avec des fibres optiques produit un effet de peau lumineuse.", type: "expérimentation" }],
    maintenant: { cherche: "Le bon équilibre entre le dispositif visible et l'effet immersif.", avancee: "La structure est montée.", bloque: null, prochaine: "Première résidence à La Friche Belle de Mai.", question: "À partir de quel moment un dispositif technique devient-il invisible ?" },
    references: [{ title: "Matter and Memory", author: "Henri Bergson", year: "1896" }],
  },
  {
    id: "la-monade", wp_id: 0, title: "La Monade", category: "rech.", status: "recherche",
    year: "2022–", question: "Comment peut-on être fermé et résonant à la fois ?",
    manifeste: "L'unité irréductible. Ce qui ne peut se diviser sans cesser d'être.",
    description: "Un projet traversant la philosophie leibnizienne, la physique quantique et la création plastique.",
    lastUpdated: "15 déc. 2024", themes: ["matière","perception","mémoire","vivant","technologie"],
    tags: ["Installation","Philosophie","Écriture"],
    image: "https://images.unsplash.com/photo-1617538716228-213f468a2c6c?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 37,
    journal: [{ date: "15 déc. 2024", title: "Leibniz et le quantique", content: "La mécanique quantique comme confirmation de la monadologie.", type: "hypothèse" }],
    maintenant: { cherche: "La forme plastique qui traduit la tension entre fermeture et résonance.", avancee: "Le corpus théorique est solide.", bloque: "Le passage de la théorie à la forme.", prochaine: "Ateliers d'expérimentation.", question: "Qu'est-ce qui distingue la résonance de l'écho ?" },
    references: [{ title: "Monadologie", author: "Gottfried Leibniz", year: "1714" }],
  },
  {
    id: "futur-animiste", wp_id: 0, title: "Futur animiste", category: "fiction", status: "terminé",
    year: "2023", question: "Que se passe-t-il lorsqu'on prend au sérieux l'idée que tout est vivant ?",
    manifeste: "2050. Quand les formes du vivant redeviennent politiques.",
    description: "Un projet de design fiction explorant un monde où l'animisme est devenu le principe organisateur des sociétés.",
    lastUpdated: "Juin 2023", themes: ["politique","vivant","technologie","transformation"],
    tags: ["Design fiction","Écologie","Politique"],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 18, journal: [],
    maintenant: { cherche: "—", avancee: "Projet terminé.", bloque: null, prochaine: "Publication d'un livret.", question: "—" },
    references: [],
  },
  {
    id: "fragments-joaillerie", wp_id: 0, title: "Fragments — Joaillerie", category: "joail.", status: "production",
    year: "2021–", question: "Une pièce peut-elle porter la mémoire d'un corps sans le représenter ?",
    manifeste: "Chaque pièce porte un fragment du monde qu'elle a traversé.",
    description: "Un atelier de joaillerie singulier, entre art et artisanat.",
    lastUpdated: "3 jan. 2025", themes: ["matière","mémoire","corps","soin","transformation"],
    tags: ["Joaillerie","Matière","Écriture"],
    image: "https://images.unsplash.com/photo-1624588057318-5f1b2eb81012?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 29,
    journal: [{ date: "3 jan. 2025", title: "Nouvelle collection : Soudures", content: "Une série autour des points de jonction.", type: "décision" }],
    maintenant: { cherche: "La juste relation entre le texte et la pièce.", avancee: "12 pièces finalisées.", bloque: null, prochaine: "Séance photo.", question: "À quel moment une soudure devient-elle une cicatrice ?" },
    references: [],
  },
  {
    id: "direction-artistique", wp_id: 0, title: "Direction artistique", category: "graph.", status: "production",
    year: "2019–", question: "L'image peut-elle être un argument politique sans perdre sa force esthétique ?",
    manifeste: "L'image comme argument. Le graphisme comme prise de position.",
    description: "Projets professionnels : Bras de Fer, affiches musicales, identités visuelles.",
    lastUpdated: "11 jan. 2025", themes: ["politique","perception","transformation"],
    tags: ["Graphisme","Identité","Motion"],
    image: "https://images.unsplash.com/photo-1733232073397-80fb13ef3212?w=1400&h=900&fit=crop&auto=format",
    fragmentCount: 11, journal: [],
    maintenant: { cherche: "Des formes qui résistent à la récupération commerciale.", avancee: "Identité Bras de Fer phase 2.", bloque: null, prochaine: "Livraison système graphique.", question: "—" },
    references: [],
  },
];

export const FALLBACK_FRAGMENTS: Fragment[] = [
  { id: "f001", wp_id: 0, number: "F.001", title: "La main qui tient", date: "10 jan. 2025", type: "note",
    content: "Le geste de tenir n'est pas une prise. C'est une conversation entre la main et l'objet.",
    status: "validé", keywords: ["main","corps","geste"], projectIds: ["trois-doigts"],
    image: "https://images.unsplash.com/photo-1585571290034-3f59a2568563?w=800&h=600&fit=crop&auto=format" },
  { id: "f002", wp_id: 0, number: "F.002", title: "Leibniz lit la physique", date: "15 déc. 2024", type: "hypothèse",
    content: "Si une particule peut être intriquée avec une autre — alors Leibniz avait peut-être tout compris.",
    status: "à relire", keywords: ["quantum","monade","résonance"], projectIds: ["la-monade"] },
  { id: "f003", wp_id: 0, number: "F.003", title: "La résine pense", date: "8 jan. 2025", type: "expérience",
    content: "Premier contact de la résine translucide + fibre optique. La lumière réagit.",
    status: "transformé", keywords: ["résine","lumière","matière"], projectIds: ["oeil-matiere"],
    image: "https://images.unsplash.com/photo-1588203379102-1a06c7d2ba1f?w=800&h=600&fit=crop&auto=format" },
  { id: "f004", wp_id: 0, number: "F.004", title: "Fragment : Pierre de lune", date: "Juin 2023", type: "citation",
    content: "Elle est froide le matin. Tiède à midi. Le soir elle garde la chaleur des doigts.",
    status: "validé", keywords: ["pierre","mémoire","matière"], projectIds: ["fragments-joaillerie"] },
  { id: "f005", wp_id: 0, number: "F.005", title: "Qu'est-ce qu'un organisme qui regarde ?", date: "2 déc. 2024", type: "question",
    content: "La caméra comme organe. Pas comme outil.",
    status: "brut", keywords: ["regard","organe","perception"], projectIds: ["oeil-matiere","la-monade"] },
  { id: "f006", wp_id: 0, number: "F.006", title: "Échec de l'animation réaliste", date: "5 jan. 2025", type: "échec",
    content: "L'animation réaliste génère de l'inconfort mais pas de l'émotion. Le réalisme tue la poésie.",
    status: "transformé", keywords: ["animation","corps","manque"], projectIds: ["trois-doigts"] },
  { id: "f007", wp_id: 0, number: "F.007", title: "La soudure comme soin", date: "3 jan. 2025", type: "note",
    content: "Souder, c'est réparer. Mais une soudure n'efface pas la rupture — elle la marque.",
    status: "validé", keywords: ["soudure","soin","cicatrice"], projectIds: ["fragments-joaillerie"] },
  { id: "f008", wp_id: 0, number: "F.008", title: "Animisme 2050", date: "Mai 2023", type: "résultat",
    content: "Une société animiste doit inventer de nouveaux droits. Droits des rivières, des forêts.",
    status: "validé", keywords: ["animisme","politique","vivant"], projectIds: ["futur-animiste"] },
];

export const FALLBACK_RESEARCH: ResearchQuestion[] = [
  { id: "q1", wp_id: 0, question: "Comment une matière peut-elle sembler nous regarder ?", projectIds: ["oeil-matiere","la-monade"], fragmentCount: 7, lastUpdated: "8 jan. 2025" },
  { id: "q2", wp_id: 0, question: "Comment représenter un corps sans le réduire à son anatomie ?", projectIds: ["trois-doigts","fragments-joaillerie"], fragmentCount: 12, lastUpdated: "10 jan. 2025" },
  { id: "q3", wp_id: 0, question: "Une image peut-elle devenir un organisme ?", projectIds: ["oeil-matiere","la-monade"], fragmentCount: 5, lastUpdated: "2 déc. 2024" },
  { id: "q4", wp_id: 0, question: "Comment documenter une expérience sensible ?", projectIds: ["oeil-matiere","trois-doigts","fragments-joaillerie"], fragmentCount: 9, lastUpdated: "3 jan. 2025" },
  { id: "q5", wp_id: 0, question: "Qu'est-ce qui reste quand on retire la forme ?", projectIds: ["la-monade","futur-animiste"], fragmentCount: 4, lastUpdated: "15 déc. 2024" },
];

export const FALLBACK_TEXTS: Text[] = [
  { id: "t1", wp_id: 0, title: "Le corps incomplet", date: "Mars 2024", type: "Essai", readTime: "8 min", relatedProjectId: "trois-doigts",
    excerpt: "Il y a dans le manque une géographie propre.",
    body: "Il y a dans le manque une géographie propre. Non pas le vide, mais la forme que prend l'air autour de ce qui n'est plus là. Le corps incomplet n'est pas un corps diminué — c'est un corps qui a appris une autre façon d'occuper l'espace." },
  { id: "t2", wp_id: 0, title: "De la matière à la lumière", date: "Nov. 2023", type: "Texte critique", readTime: "12 min", relatedProjectId: "oeil-matiere",
    excerpt: "La matière n'est pas inerte.",
    body: "La matière n'est pas inerte. Elle résiste, elle absorbe, elle diffracte. La caméra, instrument de capture, devient ici instrument d'écoute." },
  { id: "t3", wp_id: 0, title: "L'animisme comme programme politique", date: "Sept. 2023", type: "Essai", readTime: "15 min", relatedProjectId: "futur-animiste",
    excerpt: "Que se passe-t-il lorsqu'on prend au sérieux l'idée que tout est vivant ?",
    body: "Que se passe-t-il lorsqu'on prend au sérieux l'idée que tout est vivant ? Pas comme métaphore. Comme principe d'organisation sociale." },
  { id: "t4", wp_id: 0, title: "Fragment : Pierre de lune", date: "Juin 2023", type: "Fragment littéraire", readTime: "3 min", relatedProjectId: "fragments-joaillerie",
    excerpt: "Elle est froide le matin. Tiède à midi.",
    body: "Elle est froide le matin. Tiède à midi. Le soir elle garde la chaleur des doigts. Je ne sais plus si c'est la pierre qui mémorise, ou moi qui projette." },
  { id: "t5", wp_id: 0, title: "La monade et le monde", date: "Jan. 2024", type: "Recherche", readTime: "20 min", relatedProjectId: "la-monade",
    excerpt: "Leibniz dit que la monade n'a pas de fenêtre.",
    body: "Leibniz dit que la monade n'a pas de fenêtre. Et pourtant elle reflète l'univers entier. Comment peut-on être fermé et résonant à la fois ?" },
];
